In [1]:
import itertools
from sklearn.datasets import load_iris
from openpyxl import Workbook, load_workbook
from openpyxl.styles import PatternFill

In [2]:
# openpyxl.styles
from openpyxl.styles import fills
dir(fills)

['Alias',
 'Color',
 'ColorDescriptor',
 'DEFAULT_EMPTY_FILL',
 'DEFAULT_GRAY_FILL',
 'Element',
 'FILL_NONE',
 'FILL_PATTERN_DARKDOWN',
 'FILL_PATTERN_DARKGRAY',
 'FILL_PATTERN_DARKGRID',
 'FILL_PATTERN_DARKHORIZONTAL',
 'FILL_PATTERN_DARKTRELLIS',
 'FILL_PATTERN_DARKUP',
 'FILL_PATTERN_DARKVERTICAL',
 'FILL_PATTERN_GRAY0625',
 'FILL_PATTERN_GRAY125',
 'FILL_PATTERN_LIGHTDOWN',
 'FILL_PATTERN_LIGHTGRAY',
 'FILL_PATTERN_LIGHTGRID',
 'FILL_PATTERN_LIGHTHORIZONTAL',
 'FILL_PATTERN_LIGHTTRELLIS',
 'FILL_PATTERN_LIGHTUP',
 'FILL_PATTERN_LIGHTVERTICAL',
 'FILL_PATTERN_MEDIUMGRAY',
 'FILL_SOLID',
 'Fill',
 'Float',
 'GradientFill',
 'Integer',
 'MinMax',
 'NoneSet',
 'PatternFill',
 'SHEET_MAIN_NS',
 'Sequence',
 'Serialisable',
 'Set',
 'Stop',
 'StopList',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_assign_position',
 'absolute_import',
 'division',
 'fills',
 'localname',
 'safe_string']

In [3]:
iris_data = load_iris()
iris_data, iris_columns = iris_data['data'], iris_data['feature_names']
print(type(iris_data[0]), iris_columns)

<class 'numpy.ndarray'> ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
for data in iris_data[:5]:
    print(data)

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]


In [5]:
workbook = Workbook()
worksheet = workbook.active

# setting columns names
worksheet.append([column.title() for column in iris_columns])
worksheet.append(list(map(lambda c: c.title(), iris_columns)))

In [6]:
for cell in worksheet['A1': 'D1']:
    print(cell)

(<Cell 'Sheet'.A1>, <Cell 'Sheet'.B1>, <Cell 'Sheet'.C1>, <Cell 'Sheet'.D1>)


In [7]:
color = "FF0000"

# Coloring the top row
for cell in worksheet['A1':'D1'][0]:
    cell.fill = PatternFill(fgColor=color, fill_type="solid")


In [8]:
# adding data from the iris numpy.ndarray to worksheet
for data in iris_data:
    worksheet.append(list(data))


In [9]:
for row in itertools.islice(worksheet.iter_rows(), 1, None):
    for cell in row:
        if 0 <= int(cell.value) < 1:
            cell.fill = PatternFill(fgColor="00FFFF", fill_type="solid")
            
        elif 1 <= int(cell.value) < 2:
            cell.fill = PatternFill(fgColor="FF00FF", fill_type="solid")
            
        elif 2 <= int(cell.value) < 3:
            cell.fill = PatternFill(fgColor="FF0000", fill_type="solid")
            
        elif 3 <= int(cell.value) < 4:
            cell.fill = PatternFill(fgColor="EBE431", fill_type="solid")
            
        elif 4 <= int(cell.value) < 5:
            cell.fill = PatternFill(fgColor="B332EB", fill_type="solid")
            
        else:
            cell.fill = PatternFill(fgColor="FF6F00", fill_type="solid")

In [10]:
try:
    workbook.save("sample.xlsx")
    
except PermissionError:
    print("Please close any file named 'sample.xlsx'")

In [11]:
# Read Excel
workbook = load_workbook("sample.xlsx")
print(workbook.sheetnames)

['Sheet']


In [12]:
worksheet = workbook["Sheet"]

In [13]:
for row in itertools.islice(worksheet.iter_rows(), 1, None):
    for cell in row:
        if 0 <= int(cell.value) < 1:
            cell.fill = PatternFill(fgColor="00FFFF", fill_type=fills.FILL_SOLID)
            
        elif 1 <= int(cell.value)  < 2:
            cell.fill = PatternFill(fgColor="FF00FF", fill_type=fills.FILL_SOLID)
            
        elif 2 <= int(cell.value) < 3:
            cell.fill = PatternFill(fgColor="FF0000", fill_type=fills.FILL_SOLID)
            
        elif 3 <= int(cell.value) < 4:
            cell.fill = PatternFill(fgColor="EBE431", fill_type=fills.FILL_SOLID)
            
        elif 4 <= int(cell.value) < 5:
            cell.fill = PatternFill(fgColor="B332EB", fill_type=fills.FILL_SOLID)
            
        else:
            cell.fill = PatternFill(fgColor="FF6F00", fill_type=fills.FILL_SOLID)

In [14]:
try:
    new_file = "iris.xlsx"
    workbook.save("iris.xlsx")
    print(f"New data saved in the file: {new_file}")
    
except PermissionError:
    print("Please close file named 'sample.xlsx'")

New data saved in the file: iris.xlsx
