In [1]:
import itertools
from sklearn.datasets import load_iris
from openpyxl import Workbook, load_workbook
from openpyxl.styles import PatternFill

In [15]:
# openpyxl.styles
from openpyxl.styles import fills
dir(fills)

['Alias',
 'Color',
 'ColorDescriptor',
 'DEFAULT_EMPTY_FILL',
 'DEFAULT_GRAY_FILL',
 'Element',
 'FILL_NONE',
 'FILL_PATTERN_DARKDOWN',
 'FILL_PATTERN_DARKGRAY',
 'FILL_PATTERN_DARKGRID',
 'FILL_PATTERN_DARKHORIZONTAL',
 'FILL_PATTERN_DARKTRELLIS',
 'FILL_PATTERN_DARKUP',
 'FILL_PATTERN_DARKVERTICAL',
 'FILL_PATTERN_GRAY0625',
 'FILL_PATTERN_GRAY125',
 'FILL_PATTERN_LIGHTDOWN',
 'FILL_PATTERN_LIGHTGRAY',
 'FILL_PATTERN_LIGHTGRID',
 'FILL_PATTERN_LIGHTHORIZONTAL',
 'FILL_PATTERN_LIGHTTRELLIS',
 'FILL_PATTERN_LIGHTUP',
 'FILL_PATTERN_LIGHTVERTICAL',
 'FILL_PATTERN_MEDIUMGRAY',
 'FILL_SOLID',
 'Fill',
 'Float',
 'GradientFill',
 'Integer',
 'MinMax',
 'NoneSet',
 'PatternFill',
 'SHEET_MAIN_NS',
 'Sequence',
 'Serialisable',
 'Set',
 'Stop',
 'StopList',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_assign_position',
 'division',
 'fills',
 'localname',
 'safe_string']

In [2]:
iris_data = load_iris()
iris_data, iris_columns = iris_data['data'], iris_data['feature_names']
iris_columns

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
print(type(iris_data[0]))

<class 'numpy.ndarray'>


In [4]:
for data in iris_data:
    print(data)

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[5.4 3.9 1.7 0.4]
[4.6 3.4 1.4 0.3]
[5.  3.4 1.5 0.2]
[4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.4 3.7 1.5 0.2]
[4.8 3.4 1.6 0.2]
[4.8 3.  1.4 0.1]
[4.3 3.  1.1 0.1]
[5.8 4.  1.2 0.2]
[5.7 4.4 1.5 0.4]
[5.4 3.9 1.3 0.4]
[5.1 3.5 1.4 0.3]
[5.7 3.8 1.7 0.3]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.7 0.2]
[5.1 3.7 1.5 0.4]
[4.6 3.6 1.  0.2]
[5.1 3.3 1.7 0.5]
[4.8 3.4 1.9 0.2]
[5.  3.  1.6 0.2]
[5.  3.4 1.6 0.4]
[5.2 3.5 1.5 0.2]
[5.2 3.4 1.4 0.2]
[4.7 3.2 1.6 0.2]
[4.8 3.1 1.6 0.2]
[5.4 3.4 1.5 0.4]
[5.2 4.1 1.5 0.1]
[5.5 4.2 1.4 0.2]
[4.9 3.1 1.5 0.2]
[5.  3.2 1.2 0.2]
[5.5 3.5 1.3 0.2]
[4.9 3.6 1.4 0.1]
[4.4 3.  1.3 0.2]
[5.1 3.4 1.5 0.2]
[5.  3.5 1.3 0.3]
[4.5 2.3 1.3 0.3]
[4.4 3.2 1.3 0.2]
[5.  3.5 1.6 0.6]
[5.1 3.8 1.9 0.4]
[4.8 3.  1.4 0.3]
[5.1 3.8 1.6 0.2]
[4.6 3.2 1.4 0.2]
[5.3 3.7 1.5 0.2]
[5.  3.3 1.4 0.2]
[7.  3.2 4.7 1.4]
[6.4 3.2 4.5 1.5]
[6.9 3.1 4.9 1.5]
[5.5 2.3 4.  1.3]
[6.5 2.8 4.6 1.5]
[5.7 2.8 4

In [5]:
workbook = Workbook()
worksheet = workbook.active

# setting columns names
worksheet.append([column.title() for column in iris_columns])

In [6]:
# adding data from the iris numpy.ndarray to worksheet
for data in iris_data:
    worksheet.append(list(data))


In [7]:
for row in itertools.islice(worksheet.iter_rows(), 1, None):
    for cell in row:
        if 0 <= int(cell.value) < 1:
            cell.fill = PatternFill(fgColor="00FFFF", fill_type="solid")
            
        elif 1 <= int(cell.value)  < 2:
            cell.fill = PatternFill(fgColor="FF00FF", fill_type="solid")
            
        elif 2 <= int(cell.value) < 3:
            cell.fill = PatternFill(fgColor="FF0000", fill_type="solid")
            
        elif 3 <= int(cell.value) < 4:
            cell.fill = PatternFill(fgColor="EBE431", fill_type="solid")
            
        elif 4 <= int(cell.value) < 5:
            cell.fill = PatternFill(fgColor="B332EB", fill_type="solid")
            
        else:
            cell.fill = PatternFill(fgColor="FF6F00", fill_type="solid")

In [8]:
try:
    workbook.save("sample.xlsx")
    
except PermissionError:
    print("Please close file named 'sample.xlsx'")

In [9]:
# Read Excel
workbook = load_workbook("sample.xlsx")
print(workbook.sheetnames)

['Sheet']


In [12]:
worksheet = workbook["Sheet"]

In [20]:
for row in itertools.islice(worksheet.iter_rows(), 1, None):
    for cell in row:
        if 0 <= int(cell.value) < 1:
            cell.fill = PatternFill(fgColor="00FFFF", fill_type=fills.FILL_PATTERN_DARKHORIZONTAL)
            
        elif 1 <= int(cell.value)  < 2:
            cell.fill = PatternFill(fgColor="FF00FF", fill_type=fills.FILL_PATTERN_DARKHORIZONTAL)
            
        elif 2 <= int(cell.value) < 3:
            cell.fill = PatternFill(fgColor="FF0000", fill_type=fills.FILL_PATTERN_DARKHORIZONTAL)
            
        elif 3 <= int(cell.value) < 4:
            cell.fill = PatternFill(fgColor="EBE431", fill_type=fills.FILL_PATTERN_DARKHORIZONTAL)
            
        elif 4 <= int(cell.value) < 5:
            cell.fill = PatternFill(fgColor="B332EB", fill_type=fills.FILL_PATTERN_DARKHORIZONTAL)
            
        else:
            cell.fill = PatternFill(fgColor="FF6F00", fill_type=fills.FILL_PATTERN_DARKHORIZONTAL)

In [21]:
try:
    workbook.save("sample.xlsx")
    
except PermissionError:
    print("Please close file named 'sample.xlsx'")